// next
import { type NextPage } from "next";
import Head from "next/head";

// components
import { Header } from "@/components/header";
import { MetricsForm } from "@/components/metricsForm";

const Metrics: NextPage = () => {

  return (
    <>
      <Head>
        <title>Metrics</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header />
        <MetricsForm />
      </main>
    </>
  );
};

export default Metrics;
